[package]
name = "id3-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
id3 = "1.5.1"
lexopt = "0.2.1"
serde_json = "1.0.91"

[dev-dependencies]
tempfile = "3.3.0"
