[package]
name          = "id3-json"
version       = "0.2.0"
edition       = "2021"
authors       = ["Andrew Radev <andrew.radev@proton.me>"]
license       = "MIT"
description   = "Read and write ID3 tags in a machine-readable way"
readme        = "README.md"
repository    = "https://github.com/AndrewRadev/id3-image"
documentation = "https://docs.rs/id3-image/latest/id3_image"
keywords      = [ "id3", "mp3", "json" ]
categories    = [ "command-line-utilities", "filesystem" ]

[badges]
circle-ci = { repository = "AndrewRadev/id3-json" }

[dependencies]
anyhow     = "1.0.69"
id3        = "1.6.0"
lexopt     = "0.3.0"
serde_json = "1.0.94"

[dev-dependencies]
tempfile = "3.4.0"
